repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: detect-private-key
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.0.1
  hooks:
  -   id: add-trailing-comma
- repo: https://github.com/asottile/pyupgrade
  rev: v3.10.1
  hooks:
  -   id: pyupgrade
      args: [--py310-plus]
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
      language_version: python3.10
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]
